
replicaCount: 1

image:
  repository: srpl/openx_intern_task
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80
  targetPort: 5000
#  targetPort: 80
  nodePort: 30001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  failureThreshold: 2
  timeoutSeconds: 10
  httpGet:
    path: /probe
    port: 5000
  initialDelaySeconds: 10

readinessProbe:
  failureThreshold: 2
  timeoutSeconds: 10
  httpGet:
    path: /probe
    port: 5000
  initialDelaySeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
