FROM tensorflow/serving

WORKDIR /models/tfs

COPY model/saved_model /models/tfs

EXPOSE 8501

ENV MODEL_BASE_PATH=/models/tfs

CMD ["tensorflow_model_server", "--rest_api_port=8501", "--model_name=saved_model", "--model_base_path=${MODEL_BASE_PATH}"]