# FROM tensorflow/serving

# WORKDIR /models/tfs

# COPY model/saved_model.pb /models/tfs

# EXPOSE 8501

# CMD ["tensorflow_model_server", "--rest_api_port=8501", "--model_name=saved_model", "--model_base_path=/models/tfs"]